### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by OmG3r** [syonip/svelte-cordova-template#1]
Hello,

I have followed the instructions of "Get started" , however when i try to finish this step
`cd src-cordova
cordova platform add android/ios`

i get Current working directory is not a Cordova-based project.

**Comment by syonip** [comment]
Hi @OmG3r ,
Sorry I missed this.
You usually get this error when you're missing the `www` folder inside `src-cordova`.
Does it exist?

**Comment by OmG3r** [comment]
Yes i have already fixed the issue.

I would ask why the default `www` folder is not included inside `src-cordova` by default.

**Comment by syonip** [comment]
I've added a gitkeep file to make sure this folder exists when you first clone the template.
I've also added myself as a watcher to the repo so I get a notification for future issues :)

Thanks for opening the issue!
