### ISSUE TITLE
Error running application on Android Device

### ISSUE THREAD

**Issue by drannex42** [syonip/svelte-cordova-template#7]
When I run the 'npm run dev-android' it installs the application but then it throws a 'timeout' error for the server. The application works perfectly fine in the emulator. 

If I build the application, then move into the src-cordova and run 'cordova run android -l' the application will run just fine without error on the device. 

I realize this likely has to do with the Hot Reload capability are there any methods to get around this issue without completely removing? 

Thanks.

P.S: This is an absolutely awesome project.

**Comment by syonip** [comment]
Hi @drannex42 ,
When running with `npm run dev-android` there is a cordova hook that changes the main WebView to load the page from your computer's IP.
You'll see the IP in the command's output, something like:
```
updating config.xml content to http://192.168.43.12:5000
```

So you have to make sure that your device is on the same WiFi network that your computer is using, so that it can load the main app from your dev machine.

Do you see your machine's correct IP written in the output?

**Comment by drannex42** [comment]
I see that precise IP address in the output, and in the timeout error on the device. 

If I navigate to the IP address from my browser I can see the 'app'. If I navigate to that IP address on my device (plugged in to my PC, connected to the same WFi network, all firewalls disabled) it does not load, and the app that is installed will show a white screen before through a 'connection the server was unsuccessful' followed by another error saying 'Application Error: net::ERR_CONNECTION_TIMED_OUT (http://192.168.56.1:5000)

**Comment by drannex42** [comment]
The wrong IP address is being committed to the config on build, the IP address is not correct. 

I can access the App from a browser on the device, but the build tool is committing the wrong address. I'm looking into how to rewrite the config for this.

**Comment by drannex42** [comment]
This appears to be a problem with the svelte-cordova NPM package.

They are designating the IP address using getIP(), if I hardcode in my appropriate IP address the applications runs as it should on my devices.

**Comment by drannex42** [comment]
While I still believe there should be a better IP-handling method, and I will be looking into how to accomplish that (and submit a PR on svelte-cordova once I do), I found the issue is that Oracle's Virtualbox creates a wireless IP address driver that supercedes the first IP address listings. 

Once the IP address's are reorganized with your personal device on top, or you remove the driver/program from your system (or run from Docker I assume) the application will work as it should. 

I'll leave this issue up for others who may have similar issues.

**Comment by syonip** [comment]
Yeah I remember having problems running from a virtual machine too.
Did you try changing the network interface priority? This can be done on windows like here: https://www.windowscentral.com/how-change-priority-order-network-adapters-windows-10

If you find a better way to get the IP that would be great (I made the svelte-cordova npm :) )

**Comment by drannex42** [comment]
I saw that! This entire project is absolutely beautiful and opens a lot of possibilities. The directive to write in svelte, building into cordova and triggering builds is beautiful, simple (elegant), work. 

With the ability to use cordova plugins just breaks open a wide view of options. This project has sped up my development a tremendous amount and really shows that web technologies can build a tremendous and performative experience. 

I don't have anything to truly add to the project (although I will be pushing a pull request just update permissions) but I am very impressed with this. Really deserves more usage from more people. 

Thank you for developing this.

**Comment by syonip** [comment]
Thanks, glad it gave you value :)

**Comment by macleod-ee** [comment]
I figured you may make use of this, I rebuilt the usage of Svelte in hybrid apps using CapacitorJS (instead of cordova) with live reloading. https://github.com/drannex42/svelte-capacitor

I added you as a credit for inspiration at the bottom, I hope you don't mind!

**Comment by syonip** [comment]
Thanks @drannex42 , I'll check it out!
