### ISSUE TITLE
Error when running the command `npm run dev-android`

### ISSUE THREAD

**Issue by andrelmlins** [syonip/svelte-cordova-template#9]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 cordova-run-android: `cd src-cordova && cordova run android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 cordova-run-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrelmlins/.npm/_logs/2020-04-14T16_23_47_998Z-debug.log
ERROR: "cordova-run-android" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 dev-android: `cross-env CORDOVA_PLATFORM=android run-p serve:cordova autobuild cordova-run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 dev-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrelmlins/.npm/_logs/2020-04-14T16_23_48_086Z-debug.log

**Comment by MartinElsaesser** [comment]
Try `npm install cross-env`
